alfonsineprints/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings;
from django.conf.urls.static import static;

urlpatterns = [
    path('admin/', admin.site.urls),
	path('scenery/', include('scenery.urls')),
	path('astronomy/', include('astronomical_contents.urls')),
	path('works/', include('works.urls')),
	path('sources/', include('source_materials.urls')),
	path('edition/', include('edition.urls')),
	path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT);

edition/urls.py
from django.urls import path;

from . import views;

app_name = "edition";

urlpatterns = [
	path('', views.CorpusIndexView.as_view(), name="index"),
	path('corpus/<int:pk>', views.titles_index, name="corpus_index"),
	path('corpus', views.titles_index, name="orphans_index"),
	path('source/<int:pk>', views.WitnessDetailView.as_view(), name="witness"),
	path('table/<int:pk>', views.TableDetailView.as_view(), name="table"),
	path('tables/compare/<int:first>/<int:second>', views.compare_tables, name="compare-tables"),
	path('tables/compare/<int:first>', views.compare_tables, name="compare-tables"),
	path('compare/<int:first>/<int:second>', views.compare_witness, name="compare-witness"),
];

works/urls.py
from django.urls import path;

from . import views;

app_name = "works"

urlpatterns = [
	path('', views.CorpusIndexView.as_view(), name="index"),
	path('corpus/<int:pk>', views.CorpusDetailView.as_view(), name="corpus"),
	path('title/<int:pk>', views.TitleDetailView.as_view(), name="title"),
	path('actor/<int:pk>', views.ActorDetailView.as_view(), name="actor"),
];

edition/models.py
import asyncio;

from django.db import models;
from django.utils.translation import gettext_lazy as _;

from commons import network;
from source_materials.models import Witness;
from astronomical_contents.models import TableType;

from .managers import TableManager;

class Table(models.Model):
	""" Representation of one paricular table in one particlar witness """

	objects = TableManager();

	witness = models.ForeignKey(
		Witness,
		verbose_name = _("witness"),
		on_delete=models.CASCADE,
		help_text = _("The witness from which this table can be read"),
	);
	table_type = models.ForeignKey(
		TableType,
		verbose_name = _("type"),
		on_delete=models.CASCADE,
		null=True, blank=True,
		help_text = _("The type of this table"),
	);
	original_title = models.CharField(
		_("original title"),
		max_length = 200,
		blank=True,
		help_text = _("The title of this table in the original witness")
	);
	# language = models.CharField(max_length = 20, null=True, blank=True, default="Latin");
	page_start = models.IntegerField(
		_("first page"),
		null=True, blank=True,
		help_text = _("Index of the first page of the witness containing this table (set for digital witnesses in priority)"),
	);
	page_end = models.IntegerField(
		_("last page"),
		null=True, blank=True,
		help_text = _("Index of the last page of this witness containing this table (set for digital witnesses in priority)"),
	);
	folio_start = models.CharField(
		_("first folio"),
		max_length = 10,
		blank=True,
		help_text = _("Name of the first folio containing this table in the witness (ie 'A1r')"),
	);
	folio_end = models.CharField(
		_("last folio"),
		max_length = 10,
		blank=True,
		help_text = _("Name of the last folio containing this table in the witness (ie 'A1v')"),
	);
	notes = models.TextField(
		_("notes"),
		blank=True,
		help_text = _("Custom notes about this particular table"),
	);

	def __str__(self):
		if self.original_title:
			return self.original_title
		return f"{self.table_type.__str__()} in {self.witness.__str__()}";

	def get_images_url(self):
		if not self.witness.iiif_manifest:
			return [];
		manifest = asyncio.run(network.get_json(self.witness.iiif_manifest, {}));
		if None == manifest:
			return [];
		canvases = manifest['sequences'][0]['canvases'];
		pages = canvases[self.page_start-1:self.page_end];
		meta_images = [p['images'][0]['resource']['service']['@id'] for p in pages];
		images = [f"{url}/full/full/0/default.jpg" for url in meta_images];
		return images;

edition/views.py
from django.shortcuts import render, get_object_or_404;
from django.views import generic;
from django.utils.translation import gettext_lazy as _;
from django.core.exceptions import ObjectDoesNotExist as DoesNotExist;

import logging;

from works.models import Title, Corpus;
from source_materials.models import Witness;
from .models import Table;

logger = logging.getLogger(__name__);

class CorpusIndexView(generic.ListView):
	context_object_name = "corpuses_list";
	template_name = "edition/index.html"

	def get_queryset(self):
		return Corpus.objects.all().order_by("composition_date", "name");

def titles_index(request, pk = None):
	if None == pk:
		context = {
			"corpus_name": _("No corpus"),
			"titles_list": Title.objects.filter(corpus__isnull=True).order_by("print_date"),
		};
		return render(request, "edition/list_tables_in_corpus.html", context);
	corpus = get_object_or_404(Corpus, pk=pk);
	context = {
		"corpus_name": corpus.__str__(),
		"corpus": corpus,
		"titles_list": corpus.titles.order_by("print_date"),
	}
	return render(request, "edition/list_tables_in_corpus.html", context);


class WitnessDetailView(generic.DetailView):
	model = Witness;
	template_name = "edition/witness_detail.html";

class TableDetailView(generic.DetailView):
	model = Table;

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs);
		table = context["table"];
		context["other_tables"] = Table.objects.filter(table_type=table.table_type).exclude(pk=table.pk).all();
		all_tables = Table.objects.filter(witness=table.witness).order_by("page_start");
		neighbors = list(all_tables.all());
		i = neighbors.index(table);
		previous_table = neighbors[i-1] if i > 0 else None;
		next_table = neighbors[i+1] if i + 1 < len(neighbors) else None;
		context["previous_table"] = previous_table;
		context["next_table"] = next_table;
		return context;

def compare_tables(request, first, second=None):
	context = {};
	table = get_object_or_404(Table, pk=first);
	context["table"] = table;

	if None == second:
		try:
			second = request.GET["to"];
		except KeyError:
			pass;

	try:
		context["compare"] = Table.objects.get(pk=second);
	except DoesNotExist:
		pass;
	context["other_tables"] = Table.objects.filter(table_type=table.table_type).exclude(pk=table.pk).all();
	return render(request, "edition/table_compare.html", context);

def compare_witness(request, first, second):
	context = {
		"first_witness": get_object_or_404(Witness, pk=first),
		"second_witness": get_object_or_404(Witness, pk=second),
	};
	return render(request, "edition/witness_compare.html", context);

edition/templates/edition/part/list_tables_for_title.html
{% load i18n %}
<ul>
  {% for witness in title.witnesses.all %}
    <li>
      <hr>
      <small class="tag">{{ witness.table_set.count }}</small>
      {% include 'source_materials/part/witness_element.html' with witness=witness link_to="edition" %}
      <!--
      {% include 'edition/part/list_tables_for_witness.html' with witness=witness %}
      -->
    </li>
  {% endfor %}
</ul>

edition/templates/edition/part/list_tables_for_witness.html
{% load i18n %}
<table class="sortable">
  <tr>
    <th>{% translate "Pages" %}</th>
    <th>{% translate "Folio" %}</th>
    <th>{% translate "Original title" %}</th>
    <th>{% translate "Table type" %}</th>
    <th>{% translate "Astronomical object" %}</th>
  </tr>
  {% for table in witness.table_set.all %}
    <tr
      {% if table.table_type.astronomical_object and table.table_type.astronomical_object.color %}
        style="background-image:linear-gradient(270deg, {{ table.table_type.astronomical_object.color}} 0%, transparent 10%)"
      {% endif %}>
      <td {% if table.page_start %}sorttable_customkey="{{table.page_start}}"{% elif table.page_end %}sorttable_custum_key="{{table.page_end}}"{% endif %}>
        {% if table.page_start or table.page_end %}
          {% if table.witness.iiif_manifest %}
            <a href="{% url 'edition:table' table.id %}">
          {% endif %}
          {% if table.page_start and table.page_end and not table.page_start == table.page_end %}
            pp.
          {% else %}
            p.
          {% endif %}
          {% if table.page_start %}
            {{ table.page_start }}
          {% endif %}
          {% if table.page_end and not table.page_start == table.page_end %}
            - {{ table.page_end }}
          {% endif %}
          {% if table.witness.iiif_manifest %}
            </a>
          {% endif %}
        {% endif %}
      </td>
      <td {% if table.folio_start %}sorttable_customkey="{{table.folio_start}}"{% elif table.folio_end %}sorttable_custum_key="{{table.folio_end}}"{% endif %}>
        {% if table.folio_start or table.folio_end %}
          {% if table.witness.iiif_manifest %}
            <a href="{% url 'edition:table' table.id %}">
          {% endif %}
          {% if table.folio_start and table.folio_end and not table.folio_start == table.folio_end%}
            ff.
          {% else %}
            f.
          {% endif %}
          {% if table.folio_start %}
            {{ table.folio_start }}
          {% endif %}
          {% if table.folio_end and not table.folio_start == table.folio_end%}
            - {{ table.folio_end }}
          {% endif %}
          {% if table.witness.iiif_manifest %}
            </a>
          {% endif %}
        {% endif %}
      </td>
      <td>
        <a href="{% url 'edition:table' table.id %}">
          {{ table.original_title }}
        </a>
      </td>
      <td>
        {{ table.table_type.get_name }}
      </td>
      <td>
        {{ table.table_type.astronomical_object }}
      </td>
    </tr>
  {% endfor %}
  <tr>
    <td colspan=5>
      <a class="btn" href="{% url 'admin:edition_table_add' %}?witness={{ witness.id }}">
        {% translate "Add a new table" %}
      </a>
    </td>
  </tr>
</table>

edition/templates/edition/part/table_detail.html
{% load i18n %}

<section class="details">
  <h3>{% translate "Details" %}</h3>
  <dl>
    <dt>{% translate "From the Title" %}</dt>
    <dd>{% include "works/part/title_element.html" with title=table.witness.title %}</dd>
    <dt>{% translate "Source" %}</dt>
    <dd>{{ table.witness }}</dd>
    <dt>{% translate "Table type" %}</dt>
    <dd>
      {% if table.table_type %}
        <em>
          {{ table.table_type }}
        </em>
        <br/>
        {{ table.table_type.definition }}
      {% else %}
        <em>
          {% translate "No table type defined" %}
        </em>
      {% endif %}
    </dd>
    {% if table.original_title %}
      <dt>{% translate "Original title of the table" %}</dt>
      <dd>{{ table.original_title }}</dd>
    {% endif %}
    <dt>{% translate "Pages" %}</dt>
    <dd>
      {{ table.page_start }}{% if table.page_end != table.page_start %}-{{ table.page_end }}{% endif %}
      {% if table.folio_start or table.folio_end %}
        ({{ table.folio_start }}
        {% if table.folio_start != table.folio_end %}
          - {{ table.folio_end }}{% endif %})
        {% endif %}
    </dd>
    {% if table.notes %}
      <dt>{% translate "Notes about this table" %}</dt>
      <dd>{{ table.notes|linebreaks }}</dd>
    {% endif %}
  </dl>
</section>

edition/templates/edition/part/witnesses_list.html
<ul>
  {% for witness in title.witnesses.all %}
  <li>{% include 'edition/witness_name.html' with witness=witness %}</li>
  {% endfor %}
</ul>

edition/templates/edition/part/witnesses_list_by_corpus.html
<ul>
  {% for corpus in corpuses_list %}
  <li>
	<h2><a href="{% url 'works:corpus' corpus.id %}">{{ corpus.name }}</a></h2>
	{% include "edition/part/witnesses_list_by_title.html" with corpus=corpus %}
  </li>
  {% endfor %}
  {% if alone_titles %}
  <li>
	<h2>Titles without category</h2>
	<ul>
	  {% for title in alone_titles %}
	  {% include "works/part/title_name.html" with title=title %}
	  {% include "edition/part/witnesses_list.html" with title=title %}
	  {% endfor %}
	</ul>
  </li>
  {% endif %}
</ul>

edition/templates/edition/part/witnesses_list_by_title.html
<ul>
  {% for title in corpus.titles.all %}
  <li>
	{% include "works/part/title_name.html" with title=title title_url=title_url %}
	{% include "edition/part/witnesses_list.html" with title=title %}
  </li>
  {% endfor %}
</ul>