alfonsineprints/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings;
from django.conf.urls.static import static;

urlpatterns = [
    path('admin/', admin.site.urls),
	path('scenery/', include('scenery.urls')),
	path('astronomy/', include('astronomical_contents.urls')),
	path('works/', include('works.urls')),
	path('sources/', include('source_materials.urls')),
	path('edition/', include('edition.urls')),
	path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT);

edition/urls.py
from django.urls import path;

from . import views;

app_name = "edition";

urlpatterns = [
	path('', views.CorpusIndexView.as_view(), name="index"),
	path('corpus/<int:pk>', views.titles_index, name="corpus_index"),
	path('corpus', views.titles_index, name="orphans_index"),
	path('source/<int:pk>', views.WitnessDetailView.as_view(), name="witness"),
	path('table/<int:pk>', views.TableDetailView.as_view(), name="table"),
	path('tables/compare/<int:first>/<int:second>', views.compare_tables, name="compare-tables"),
	path('tables/compare/<int:first>', views.compare_tables, name="compare-tables"),
	path('compare/<int:first>/<int:second>', views.compare_witness, name="compare-witness"),
];

works/urls.py
from django.urls import path;

from . import views;

app_name = "works"

urlpatterns = [
	path('', views.CorpusIndexView.as_view(), name="index"),
	path('corpus/<int:pk>', views.CorpusDetailView.as_view(), name="corpus"),
	path('title/<int:pk>', views.TitleDetailView.as_view(), name="title"),
	path('actor/<int:pk>', views.ActorDetailView.as_view(), name="actor"),
];

edition/models.py
import asyncio;

from django.db import models;
from django.utils.translation import gettext_lazy as _;

from commons import network;
from source_materials.models import Witness;
from astronomical_contents.models import TableType;

from .managers import TableManager;

class Table(models.Model):
	""" Representation of one paricular table in one particlar witness """

	objects = TableManager();

	witness = models.ForeignKey(
		Witness,
		verbose_name = _("witness"),
		on_delete=models.CASCADE,
		help_text = _("The witness from which this table can be read"),
	);
	table_type = models.ForeignKey(
		TableType,
		verbose_name = _("type"),
		on_delete=models.CASCADE,
		null=True, blank=True,
		help_text = _("The type of this table"),
	);
	original_title = models.CharField(
		_("original title"),
		max_length = 200,
		blank=True,
		help_text = _("The title of this table in the original witness")
	);
	# language = models.CharField(max_length = 20, null=True, blank=True, default="Latin");
	page_start = models.IntegerField(
		_("first page"),
		null=True, blank=True,
		help_text = _("Index of the first page of the witness containing this table (set for digital witnesses in priority)"),
	);
	page_end = models.IntegerField(
		_("last page"),
		null=True, blank=True,
		help_text = _("Index of the last page of this witness containing this table (set for digital witnesses in priority)"),
	);
	folio_start = models.CharField(
		_("first folio"),
		max_length = 10,
		blank=True,
		help_text = _("Name of the first folio containing this table in the witness (ie 'A1r')"),
	);
	folio_end = models.CharField(
		_("last folio"),
		max_length = 10,
		blank=True,
		help_text = _("Name of the last folio containing this table in the witness (ie 'A1v')"),
	);
	notes = models.TextField(
		_("notes"),
		blank=True,
		help_text = _("Custom notes about this particular table"),
	);

	def __str__(self):
		if self.original_title:
			return self.original_title
		return f"{self.table_type.__str__()} in {self.witness.__str__()}";

	def get_images_url(self):
		if not self.witness.iiif_manifest:
			return [];
		manifest = asyncio.run(network.get_json(self.witness.iiif_manifest, {}));
		if None == manifest:
			return [];
		canvases = manifest['sequences'][0]['canvases'];
		pages = canvases[self.page_start-1:self.page_end];
		meta_images = [p['images'][0]['resource']['service']['@id'] for p in pages];
		images = [f"{url}/full/full/0/default.jpg" for url in meta_images];
		return images;

edition/views.py
from django.shortcuts import render, get_object_or_404;
from django.views import generic;
from django.utils.translation import gettext_lazy as _;
from django.core.exceptions import ObjectDoesNotExist as DoesNotExist;

import logging;

from works.models import Title, Corpus;
from source_materials.models import Witness;
from .models import Table;

logger = logging.getLogger(__name__);

class CorpusIndexView(generic.ListView):
	context_object_name = "corpuses_list";
	template_name = "edition/index.html"

	def get_queryset(self):
		return Corpus.objects.all().order_by("composition_date", "name");

def titles_index(request, pk = None):
	if None == pk:
		context = {
			"corpus_name": _("No corpus"),
			"titles_list": Title.objects.filter(corpus__isnull=True).order_by("print_date"),
		};
		return render(request, "edition/list_tables_in_corpus.html", context);
	corpus = get_object_or_404(Corpus, pk=pk);
	context = {
		"corpus_name": corpus.__str__(),
		"corpus": corpus,
		"titles_list": corpus.titles.order_by("print_date"),
	}
	return render(request, "edition/list_tables_in_corpus.html", context);


class WitnessDetailView(generic.DetailView):
	model = Witness;
	template_name = "edition/witness_detail.html";

class TableDetailView(generic.DetailView):
	model = Table;

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs);
		table = context["table"];
		context["other_tables"] = Table.objects.filter(table_type=table.table_type).exclude(pk=table.pk).all();
		all_tables = Table.objects.filter(witness=table.witness).order_by("page_start");
		neighbors = list(all_tables.all());
		i = neighbors.index(table);
		previous_table = neighbors[i-1] if i > 0 else None;
		next_table = neighbors[i+1] if i + 1 < len(neighbors) else None;
		context["previous_table"] = previous_table;
		context["next_table"] = next_table;
		return context;

def compare_tables(request, first, second=None):
	context = {};
	table = get_object_or_404(Table, pk=first);
	context["table"] = table;

	if None == second:
		try:
			second = request.GET["to"];
		except KeyError:
			pass;

	try:
		context["compare"] = Table.objects.get(pk=second);
	except DoesNotExist:
		pass;
	context["other_tables"] = Table.objects.filter(table_type=table.table_type).exclude(pk=table.pk).all();
	return render(request, "edition/table_compare.html", context);

def compare_witness(request, first, second):
	context = {
		"first_witness": get_object_or_404(Witness, pk=first),
		"second_witness": get_object_or_404(Witness, pk=second),
	};
	return render(request, "edition/witness_compare.html", context);

edition/templates/edition/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Tables by corpus" %}{% endblock %}
{% block page_title %}{% translate "Tables by corpus" %}{% endblock %}

{% block content %}
  <ol>
    {% for corpus in corpuses_list %}
      <li>
        <h2>
          <a href="{% url 'edition:corpus_index' corpus.id %}">{{ corpus }}</a>
        </h2>
      </li>
    {% endfor %}
    <li>
      <h2>
        <a href="{% url 'edition:orphans_index' %}">{% translate "Orphan titles" %}</a>
      </h2>
    </li>
  </ol>
{% endblock %}

edition/templates/edition/list_tables_in_corpus.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {% blocktranslate with corpus_name=corpus_name %}List of tables in the {{corpus_name }} corpus{% endblocktranslate %}
{% endblock %}
{% block page_title %}
  {% blocktranslate with corpus_name=corpus_name %}List of tables in the {{corpus_name }} corpus{% endblocktranslate %}
{% endblock %}
{% block nav %}
  <a class="btn" href="{% url 'edition:index' %}">{% translate "Back to the list of corpuses" %}</a>
{% endblock %}
{% block content %}
  <ol>
    {% for title in titles_list.all %}
      <li>
        <hr>
        {% include 'works/part/title_element.html' with title=title %}
        {% include 'edition/part/list_tables_for_title.html' with title=title %}
      </li>
    {% endfor %}
  </ol>
{% endblock %}

edition/templates/edition/table_compare.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ table }} - {{ compare }}{% endblock %}
{% block page_title %}{{ table }} - {{ compare }}{% endblock %}

{% block nav %}
  <a class="btn" href="{% url 'edition:table' table.id %}">{% translate "Return to table" %}</a>
{% endblock %}

{% block content %}
  <section class="compare">
    <aside>
      <h3>
        <em>{{ table.witness }}</em>,
        f.{{ table.folio_start }}-{{ table.folio_end }} : {{ table.table_type }}
      </h3>
      <a href="{% url 'edition:table' table.id %}">{% translate "See details" %}</a>
      <p>
        <em>{% include 'works/part/title_element.html' with title=table.witness.title %}</em>
      </p>
{% for image in table.get_images_url %}
  <img src="{{image}}" alt="{% translate 'Scanned pages' %}"/>
{% endfor %}
</aside>
<aside>
  {% if compare %}
    <h3>
      <em>{{ compare.witness }}</em>
      f.{{ compare.folio_start }}-{{ compare.folio_end }} : {{ compare.table_type }}
    </h3>
    <a href="{% url 'edition:table' compare.id %}">{% translate "See details" %}</a>
    <p>
      <em>{% include 'works/part/title_element.html' with title=compare.witness.title %}</em>
      </p>
    {% for image in compare.get_images_url %}
      <img src="{{image}}" alt="{% translate 'Scanned pages' %}"/>
    {% endfor %}
  {% else %}
    <form action="" method="get">
      <select name="to">
        {% for other in other_tables %}
          <option value="{{other.id}}">p.{{ other.page_start }} - {{ other.witness }}</option>
        {% endfor %}
      </select>
      <input type="submit" value="{% translate 'compare' %}">
    </form>
  {% endif %}
</aside>
</section>
{% endblock %}

edition/templates/edition/table_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ table }}{% endblock %}
{% block page_title %}{{ table }}{% endblock %}

{% block nav %}
  <a class="btn" href="{% url 'edition:witness' table.witness.id %}">{% translate "Table of content" %}</a>
{% endblock %}

{% block content %}
  {% if previous_table %}
    <a class="btn" href="{% url 'edition:table' previous_table.id %}">
      {% translate "Previous table" %}
    </a>
  {% else %}
    <em>{% translate "First table" %}</em>
  {% endif %}
  {% if next_table %}
    <a class="btn" href="{% url 'edition:table' next_table.id %}">
      {% translate "Next table" %}
    </a>
  {% else %}
    <em>{% translate "Last table" %}</em>
  {% endif %}
  <a class="btn" href="{% url 'admin:edition_table_add' %}?witness={{ table.witness.id }}">
    {% translate "Add a new table" %}
  </a>

  {% include 'edition/part/table_detail.html' with table=table %}

{% if table.get_images_url %}
  <form action="{% url 'edition:compare-tables' table.id %}" method="get">
    <select name="to">
      {% for other in other_tables %}
        <option value="{{other.id}}">p.{{ other.page_start }} - {{ other.witness }}</option>
      {% endfor %}
    </select>
    <input type="submit" value="{% translate 'compare' %}">
  </form>
  <section class="compare">
    <aside>
      <h3>{% translate "Scanned pages" %}</h3>
      {% for image in table.get_images_url %}
        <img src="{{image}}" alt="{% translate 'Scanned pages' %}"/>
      {% endfor %}
    </aside>
    <aside>
      <h3>{% translate "Table type:" %} {{table.table_type}}</h3>
      {% include 'astronomical_contents/table_exemple.html' with tabletype=table.table_type %}
    </aside>
  </section>
{% elif table.table_type and table.table_type.table_edition %}
  <section>
      <h3>{% translate "Table type:" %} {{table.table_type}}</h3>
      {% include 'astronomical_contents/table_exemple.html' with tabletype=table.table_type %}
  </section>
{% endif %}

  {% if previous_table %}
  <a class="btn" href="{% url 'edition:table' previous_table.id %}">
    {% translate "Previous table" %}
  </a>
{% endif %}
{% if next_table %}
  <a class="btn" href="{% url 'edition:table' next_table.id %}">
    {% translate "Next table" %}
  </a>
  {% endif %}
{% endblock %}

edition/templates/edition/witness_compare.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ first_witness }} - {{ second_witness }}{% endblock %}
{% block page_title %}{% translate "Compare" %}{% endblock %}

{% block nav %}
  <a class="btn" href="{% url 'edition:witness' first_witness.id %}">{% translate "Return to source" %}</a>
{% endblock %}

{% block content %}
  <section class="compare">
    <aside>
      <h3>
        <em>{{ first_witness }}</em>,
      </h3>
      <a href="{% url 'edition:witness' first_witness.id %}">{% translate "See details" %}</a>
      <p>
        <em>{% include 'works/part/title_element.html' with title=first_witness.title %}</em>
      </p>
      {% include 'edition/part/list_tables_for_witness.html' with witness=first_witness %}
</aside>
<aside>
    <h3>
      <em>{{ second_witness }}</em>
    </h3>
    <a href="{% url 'edition:witness' second_witness.id %}">{% translate "See details" %}</a>
    <p>
      <em>{% include 'works/part/title_element.html' with title=second_witness.title %}</em>
    </p>
    {% include 'edition/part/list_tables_for_witness.html' with witness=second_witness %}
</aside>
</section>
{% endblock %}

edition/templates/edition/witness_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ witness }} | {{ witness.title }}{% endblock %}
{% block page_title %}{{ witness }}{% endblock %}

{% block nav %}
  <a class="btn" href="{% url 'edition:index' %}">{% translate "Back to index" %}</a>
{% endblock %}

{% block content %}

  {% include 'source_materials/part/witness_detail.html' with witness=witness %}
  <article>
    <header>
      <h2>{% translate "List of tables in this book" %}</h2>
      <a class="btn"
         href="{% url 'admin:edition_table_add' %}?witness={{ witness.id }}">
         {% translate "Add a new table" %}
      </a>
    </header>
    {% include 'edition/part/list_tables_for_witness.html' with witness=witness %}
  </article>
{% endblock %}

edition/templates/edition/witness_name.html
{% if witness.library %}
{% include 'source_materials/library_name.html' with library=witness.library %}
{% if witness.shelf_mark %}
Shelf mark {{ self.witness_mark }}
{% endif %}
{% endif %}
{% if witness.get_link %}
<a href="{{ witness.get_link }}">
  {% if witness.iiif_manifest %}
  IIIF Manifest
  {% elif witness.url %}
  URL
  {% else %}
  URN
  {% endif %}
</a>
{% endif %}
<a href="{% url 'edition:witness' witness.id %}">&gt&gtDetails</a>