alfonsineprints/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings;
from django.conf.urls.static import static;

urlpatterns = [
    path('admin/', admin.site.urls),
	path('scenery/', include('scenery.urls')),
	path('astronomy/', include('astronomical_contents.urls')),
	path('works/', include('works.urls')),
	path('sources/', include('source_materials.urls')),
	path('edition/', include('edition.urls')),
	path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT);

source_materials/urls.py
from django.urls import path;

from . import views;

app_name = "sources";

urlpatterns = [
	path('', views.CorpusIndexView.as_view(), name="index"),
	path('title/<int:pk>', views.TitleDetailView.as_view(), name="title"),
	path('witness/<int:pk>', views.WitnessDetailView.as_view(), name="witness"),
];

works/urls.py
from django.urls import path;

from . import views;

app_name = "works"

urlpatterns = [
	path('', views.CorpusIndexView.as_view(), name="index"),
	path('corpus/<int:pk>', views.CorpusDetailView.as_view(), name="corpus"),
	path('title/<int:pk>', views.TitleDetailView.as_view(), name="title"),
	path('actor/<int:pk>', views.ActorDetailView.as_view(), name="actor"),
];

source_materials/models.py
from urllib.parse import urlparse;

from django.db import models;
from django.utils.translation import gettext_lazy as _;

from scenery.models import Place;
from works.models import Title;

from .managers import LibraryManager, WitnessManager;

class Library(models.Model):
	""" Stores information about a library, or other holding site of a printed witness. """

	@staticmethod
	def ontology():
		return {
			"keys": {
				"cerl_id": "data.cerl.org",
				"dishas_id": "dishas.obspm.fr",
			},
			"sources": {
				"data.cerl.org": {
					"_id": "cerl_id",
					"name": "name",
					"geonamesId": "location",
					"country": "country_code",
					"isil": "isil",
				},
				"dishas.obspm.fr": {
					"kibana_name": "name",
					"kibana_id": "dishas_id",
				},
			},
		};

	objects = LibraryManager();

	class Meta:
		verbose_name = _("library");
		verbose_name_plural = _("libraries");


	#   ===   Database informations   ===
	dishas_id = models.CharField(
		_("Dishas' identifier"),
		max_length = 100,
		null = True, unique = True,
		blank = True,
		help_text = _("Identifier of the library in the dishas' elastic-search API"),
	);

	cerl_id = models.CharField(
		_("cerl.org identifier"),
		max_length = 200,
		null = True, unique = True,
		blank = True,
		help_text = _("Identifier of the library on data.cerl.org/holdinst"),
	);

	#   ===   Basic informations   ===
	name = models.CharField(
		_("name"),
		max_length = 200,
		blank = True,
		help_text = _("Name of the library"),
	);

	location = models.ForeignKey(
		Place,
		verbose_name=_("location"),
		on_delete = models.CASCADE,
		null = True, blank = True,
		help_text = _("Where the library is situated"),
	);

	country_code = models.CharField(
		_("country code"),
		max_length = 3,
		blank = True,
		help_text = _("Nationality of the library following ISO 3166-1 alpha convention"),
	);

	isil = models.CharField(
		_("isil number"),
		max_length = 16,
		blank = True,
		help_text = _("International Standard Identifier for Libraries and Related Organizations, norm ISO 15511"),
	);


	#   ===   Sources   ===
	data_sources = models.TextField(
		_("sources of the informations"),
		blank=True,
		help_text = _("Source of the informations stored about this library"),
	);


	class Meta:
		verbose_name = "library";
		verbose_name_plural = "libraries";

	def __str__(self):
		return self.name;


class Witness(models.Model):
	""" Informations about one particular version of an eddited title """

	@staticmethod
	def ontology():
		return {
			"keys": {},
			"sources": {
				"heurist.huma-num.fr": {
					"IIIF Manifest": "iiif_manifest",
					"Digitization URL": "url",
					"Catalog URL": "catalog_url",
				},
			},
		};

	objects = WitnessManager();

	class Meta:
		verbose_name = _("witness");
		verbose_name_plural = _("witnesses");

	#   ===   Database links   ===
	dishas_id = models.IntegerField(
		_("Dishas identifier"),
		null = True, blank = True,
		help_text = _("Identifier of the source in the dishas' huma-num database"),
	);

	#   ===   Identification informations   ===
	name = models.CharField(
		max_length = 100,
		blank = True,
		help_text = _("Name of this particular witness"),
	);

	title = models.ForeignKey(
		Title,
		verbose_name =_("title"),
		on_delete=models.CASCADE,
		related_name="witnesses",
		help_text = _("The historical edition of this witness"),
	);

	#   ===   Localization informations   ===
	library = models.ForeignKey(
		Library,
		verbose_name=_("holding site"),
		on_delete=models.CASCADE,
		related_name="holdings",
		null=True, blank = True,
		help_text=_("Institution holding this particular witness"),
	);
	shelf_mark = models.CharField(
		_("shelf mark"),
		max_length=100,
		blank=True,
		help_text=_("Identifier of this witness in the holding site's catalogue"),
	);
	catalog_url = models.CharField(
		_("catalog's url"),
		max_length = 100,
		blank = True,
		help_text = _("Location of this witness in a catalogue"),
	);

	#   ===   Digitalization informations   ===
	is_digital = models.BooleanField(
		_("is digital"),
		default = False,
		help_text=_("Is this witness available in digital format"),
	);
	url = models.CharField(
		_("URL"),
		max_length = 200,
		blank=True,
		help_text=_("Location of a digitalized version of this witness"),
	);
	urn = models.CharField(
		_("URN"),
		max_length = 200,
		blank=True,
		help_text=_("Unified Resource Name of a digitalized version of this witness"),
	);
	iiif_manifest = models.CharField(
		_("IIIF manifest"),
		max_length = 200,
		blank=True,
		help_text=_("International Image Interoperability manifest's URL"),
	);

	notes = models.TextField(
		_("notes"),
		blank=True,
		help_text = _("Free notes about this particular witness"),
	);

	#   ===   Sources   ===
	data_sources = models.TextField(
		_("sources of the informations"),
		blank=True,
		help_text = _("Source of the informations stored about this library"),
	);


	def __str__(self):
		if self.name:
			return self.name;
		if self.shelf_mark and self.library.__str__():
			library_name = self.library.__str__();
			return f"{self.shelf_mark} | {library_name}";
		if self.iiif_manifest or self.url or self.urn:
			return "Digital copy";
		return f"Witness of {self.title.name}";

	def get_link(self):
		if self.iiif_manifest:
			return f"https://dishas.obspm.fr/alfa/mirador?manifest={self.iiif_manifest}";
		if self.url:
			return self.url;
		if self.urn:
			return f"https://nbn-resolving.org/process-urn-form?identifier={self.urn}&verb=REDIRECT";
		return None

source_materials/views.py
from django.shortcuts import render;
from django.views import generic;

import logging;

from works.models import Title, Corpus;
from .models import Witness, Library;

logger = logging.getLogger(__name__);

class CorpusIndexView(generic.ListView):
	context_object_name = "corpuses_list";
	template_name = "source_materials/corpus_list.html";

	def get_queryset(self):
		return Corpus.objects.all().order_by("composition_date", "name");

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs);
		context["alone_titles"] = Title.objects.filter(corpus__isnull=True).order_by("print_date");
		return context;

class TitleDetailView(generic.DetailView):
	model = Title;
	template_name = "source_materials/title_detail.html"

class WitnessDetailView(generic.DetailView):
	model = Witness;

source_materials/templates/source_materials/corpus_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Witnesses by corpus" %}{% endblock %}
{% block page_title %}{% translate "Witnesses by corpus" %}{% endblock %}

{% block content %}
  <ul>
    {% for corpus in corpuses_list %}
      <li>
        <h2>
          {{ corpus }}
        </h2>
        <a href="{% url 'works:corpus' corpus.id %}">&gt{% translate "Details" %}</a>
        <ol>
          {% for title in corpus.titles.all %}
          <li>
            {% include 'works/part/title_element.html' with title=title link_to="sources" %}
            <ul>
              {% for witness in title.witnesses.all %}
                <li>
                  {% include 'source_materials/part/witness_element.html' with witness=witness %}
                </li>
              {% endfor %}
            </ul>
          </li>
          {% endfor %}
        </ol>
      </li>
    {% endfor %}
    <li>
      <h2>{% translate "Orphan titles" %}</h2>
      <ol>
        {% for title in alone_titles.all %}
          <li>
            {% include 'works/part/title_element.html' with title=title link_to="sources" %}
            <ul>
              {% for witness in title.witnesses.all %}
                <li>
                  {% include 'source_materials/part/witness_element.html' with witness=witness %}
                </li>
              {% endfor %}
            </ul>
          </li>
        {% endfor %}
      </ol>
    </li>
  </ul>
{% endblock %}

source_materials/templates/source_materials/title_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block page_title %}{% translate "Witnesses of a title" %}{% endblock %}

{% block nav %}
  <a href="{% url 'sources:index' %}">Go back to the list</a>
{% endblock %}

{% block content %}

  {% include 'works/part/title_detail.html' with title=title %}
  <article>
    <header>
      <h2>{% translate "List of witnesses of this title" %}</h2>
      <a class="btn"
         href="{% url 'admin:source_materials_witness_add' %}?title={{ title.id }}">
         {% translate "Add a new witness" %}
      </a>
    </header>
    <ul>
      {% for witness in title.witnesses.all %}
        <li>{% include 'source_materials/part/witness_element.html' %}</li>
      {% endfor %}
    </ul>
  </article>
{% endblock %}

source_materials/templates/source_materials/witness_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ witness }}{% endblock %}
{% block page_title %}{{ witness }}{% endblock %}

{% block nav %}
  <a href="{% url 'sources:index' %}">{% translate "Back to index" %}</a>
{% endblock %}

{% block content %}
  {% include 'source_materials/part/witness_detail.html' with witness=witness link_to='sources' %}
{% endblock %}

source_materials/templates/source_materials/witness_name.html
{% if witness.library %}
{% include 'source_materials/library_name.html' with library=witness.library %}
{% if witness.shelf_mark %}
Shelf mark {{ self.witness_mark }}
{% endif %}
{% endif %}
{% if witness.get_link %}
<a href="{{ witness.get_link }}">
  {% if witness.iiif_manifest %}
  {{ witness.iiif_manifest }}
  {% elif witness.url %}
  {{ witness.url }}
  {% else %}
  {{ witness.urn }}
  {% endif %}
</a>
{% endif %}
<a href="{% url 'sources:witness' witness.id %}">Details</a>

source_materials/templates/source_materials/witnesses_list.html
<ul>
  {% for witness in title.witnesses.all %}
  <li>{% include 'source_materials/witness_name.html' with witness=witness %}</li>
  {% endfor %}
</ul>

source_materials/templates/source_materials/witnesses_list_by_corpus.html
<ul>
  {% for corpus in corpuses_list %}
  <li>
	<h2><a href="{% url 'works:corpus' corpus.id %}">{{ corpus.name }}</a></h2>
	{% include "source_materials/witnesses_list_by_title.html" with corpus=corpus %}
  </li>
  {% endfor %}
  {% if alone_titles %}
  <li>
	<h2>Titles without category</h2>
	<ul>
	  {% for title in alone_titles %}
	  {% include "works/title_name.html" with title=title %}
	  {% include "source_materials/witnesses_list.html" with title=title %}
	  {% endfor %}
	</ul>
  </li>
  {% endif %}
</ul>

source_materials/templates/source_materials/witnesses_list_by_title.html
<ul>
  {% for title in corpus.titles.all %}
  <li>
	{% include "works/title_name.html" with title=title title_url=title_url %}
	{% include "source_materials/witnesses_list.html" with title=title %}
  </li>
  {% endfor %}
</ul>